backend:
  name: github
  repo: ddd-dong/blog
  branch: main
  base_url: https://blog-auth.dong1214-mailbox.workers.dev
  auth_endpoint: auth
media_folder: static/img
public_folder: /blog/img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }